Repository ya-pomogau/frontend-fork, pull requests merged in 2023-11, with the labels that each got.

#134 Refact/button admin
  src/shared/ui/admin-button/admin-button.module.css
  src/shared/ui/admin-button/admin-button.stories.ts
  src/shared/ui/admin-button/index.tsx
  src/widgets/header/menu/index.tsx
  src/widgets/header/menu/styles.module.css
Labels: enhancement

#132 politico + errors in the text
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  src/pages/layout/index.tsx
  src/pages/layout/styles.module.css
  src/pages/policy/content.tsx
  src/pages/policy/index.tsx
  src/pages/policy/markdown-style.module.css
  src/pages/policy/politico.stories.tsx
  src/shared/ui/page-layout/styles.module.css
  src/widgets/header/navigation/side-bar.stories.tsx
  src/widgets/header/utils.tsx
Labels: bug, frontend

#138 [Feature] System slice
  src/app/store/index.ts
  src/config/api-config.ts
  src/entities/error/model/error.ts
  src/entities/user/types.ts
  src/services/auth.ts
  src/services/auth.types.ts
  src/services/system-slice.ts
  src/shared/types/common.types.ts
  src/shared/types/store.types.ts
Labels: enhancement, frontend

#139 [Refactor] Use user entity
  .eslintrc.json
  src/entities/user/model/user.ts
  src/entities/user/types.ts
Labels: enhancement, frontend
